name: husarion-chatter-shm
version: '0.1'
license: Apache-2.0
summary: The ROS 2 chatter snap
description: |
  The husarion-chatter-shm snap demonstrates essential ROS 2 communication 
  through a talker-listener setup, ideal for educational and quick 
  development purposes. This snap deploys two nodes for real-time 
  message passing, showcasing the foundational concept of ROS 2 inter-node communication.

  To launch the integrated talker and listener demonstration, use:
    $ husarion-chatter-shm

  For launching only the talker node, which publishes messages, enter:
    $ husarion-chatter-shm.talker

  To start the listener node, which subscribes to the talker's messages, use:
    $ husarion-chatter-shm.listener

grade: stable
confinement: strict
base: core22

contact: https://github.com/husarion/rosbot-xl-teleop-snap/issues
issues: https://github.com/husarion/rosbot-xl-teleop-snap/issues
website: https://husarion.com/

architectures:
  - build-on: amd64
  - build-on: arm64

slots:
  shmem-slot:
    interface: shared-memory
    write: ['*'] # paths are relative to /dev/shm
    private: false 
plugs:
  shmem-plug:
    interface: shared-memory
    shared-memory: shmem-slot
    private: false

apps:
  husarion-chatter-shm:
    command: ros2 launch $SNAP/usr/bin/talker_listener_launch.py
    plugs: [shmem-plug, shared-memory]
    slots: [shmem-slot]
    extensions: [ros2-humble-ros-base]

  talker:
    command: usr/bin/chatter_launcher.sh talker
    plugs: [shmem-plug, shared-memory]
    slots: [shmem-slot]
    extensions: [ros2-humble-ros-base]

  listener:
    command: usr/bin/chatter_launcher.sh listener
    plugs: [shmem-plug, shared-memory]
    slots: [shmem-slot]
    extensions: [ros2-humble-ros-base]

parts:
  husarion-chatter-shm:
    plugin: nil
    stage-packages:
      - ros-humble-demo-nodes-cpp

  # copy local scripts to the snap
  local-files:
    plugin: dump
    source: snap/local/
    organize:
      '*.sh': usr/bin/
      '*.py': usr/bin/
      '*.yaml': usr/share/husarion-chatter-shm/config/
      '*.xml': usr/share/husarion-chatter-shm/config/